import React from 'react';
import { 
  Phone, Video, Mic, MicOff, Camera, Monitor, 
  UserCheck, FileText, ShieldAlert, LayoutDashboard, 
  Settings, User, LogOut, Search, MoreHorizontal,
  PhoneOff, Smartphone, CreditCard, CheckCircle2, XCircle,
  Maximize2, Share2, History, MapPin, X, ArrowLeft,
  Play, Pause, Clock, FileCheck, AlertCircle, AlertTriangle,
  ChevronRight, MessageSquare, FileSignature, Calendar, Filter,
  ArrowRight, LogIn, Power, Coffee, UserX, Download, ChevronDown,
  PieChart, TrendingUp, BarChart3, FileBadge, Image
} from 'lucide-react';

export const Icons = {
  Phone,
  Video,
  Mic,
  MicOff,
  Camera,
  Monitor,
  UserCheck,
  FileText,
  ShieldAlert,
  Dashboard: LayoutDashboard,
  Settings,
  User,
  LogOut,
  Search,
  More: MoreHorizontal,
  Hangup: PhoneOff,
  Mobile: Smartphone,
  Card: CreditCard,
  Check: CheckCircle2,
  XCircle: XCircle,
  Close: X,
  Expand: Maximize2,
  Share: Share2,
  History,
  Location: MapPin,
  ArrowLeft,
  Play,
  Pause,
  Clock,
  FileCheck,
  AlertCircle,
  AlertTriangle,
  ChevronRight,
  MessageSquare,
  FileSignature,
  Calendar,
  Filter,
  ArrowRight,
  LogIn,
  Power,
  Coffee,
  UserX,
  Download,
  ChevronDown,
  PieChart,
  TrendingUp,
  BarChart: BarChart3,
  FileBadge,
  Image
};